export const LISTA_UPDATE = 'LISTA_UPDATE';
export const PRODUTO_UPDATE = 'PRODUTO_UPDATE';
export const CARRINHO_PRODUTO_ADD = 'CARRINHO_PRODUTO_ADD';
export const CARRINHO_PRODUTO_SUB = 'CARRINHO_PRODUTO_SUB';